// /** @type {import('tailwindcss').Config} */
// export default {
//   content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
//   theme: {
//     extend: {
//       colors: {
//         "error-container": "#ffdad6",
//         "on-secondary": "#ffffff",
//         background: "#fbf9f4",
//         "surface-container-highest": "#e4e2dd",
//         "inverse-on-surface": "#f2f1ec",
//         "outline-variant": "#bec8cb",
//         "on-primary": "#ffffff",
//         "on-tertiary-fixed-variant": "#5b4137",
//         "surface-dim": "#dbdad5",
//         "tertiary-fixed": "#ffdbce",
//         "on-surface-variant": "#3f484b",
//         "secondary-fixed": "#ffdcc5",
//         primary: "#006474",
//         "secondary-container": "#ff9742",
//         "inverse-primary": "#87d2e4",
//         "on-tertiary": "#ffffff",
//         outline: "#6f797c",
//         "on-secondary-container": "#6c3400",
//         "surface-container-low": "#f5f3ee",
//         "on-background": "#1b1c19",
//         "on-error-container": "#93000a",
//         "on-tertiary-fixed": "#2b160f",
//         "on-primary-fixed-variant": "#004e5b",
//         "on-tertiary-container": "#fff8f7",
//         "surface-container-lowest": "#ffffff",
//         "tertiary-fixed-dim": "#e4beb2",
//         "on-secondary-fixed-variant": "#713700",
//         secondary: "#944a00",
//         "inverse-surface": "#30312e",
//         "primary-container": "#2d7d8e",
//         "surface-bright": "#fbf9f4",
//         "on-primary-fixed": "#001f26",
//         "primary-fixed": "#a9edff",
//         surface: "#fbf9f4",
//         "on-primary-container": "#f3fcff",
//         "on-error": "#ffffff",
//         "surface-variant": "#e4e2dd",
//         error: "#ba1a1a",
//         "surface-tint": "#086878",
//         tertiary: "#70544a",
//         "on-surface": "#1b1c19",
//         "primary-fixed-dim": "#87d2e4",
//         "surface-container": "#f0eee9",
//         "tertiary-container": "#8b6c61",
//         "secondary-fixed-dim": "#ffb783",
//         "on-secondary-fixed": "#301400",
//         "surface-container-high": "#eae8e3",
//       },
//       borderRadius: {
//         lg: "0.5rem",
//         xl: "0.75rem",
//       },
//       spacing: {
//         base: "8px",
//         "margin-mobile": "16px",
//         xl: "80px",
//         sm: "12px",
//         lg: "48px",
//         md: "24px",
//         "margin-desktop": "64px",
//         gutter: "24px",
//         xs: "4px",
//         "max-width": "1280px",
//       },
//       fontFamily: {
//         headline: ["Quicksand", "sans-serif"],
//         body: ["Plus Jakarta Sans", "sans-serif"],
//       },
//     },
//   },
//   plugins: [],
// };
